version: '3'

services:
  php:
    build:
      context: ./images/php-fpm
    container_name: ng-poc-php
    volumes:
      - ../Api:/var/www/ng-poc/Api
    links:
      - ngdb
  ngnix:
    build:
      context: ./images/ngnix
    container_name: ng-poc-ngnix
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ../Docker/logs/nginx/:/var/log/nginx
    links:
      - php
  ngdb:
    image: mariadb
    container_name: ng-poc-db
    ports:
      - '3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: ng-poc
      MARIADB_USER: usrdev
      MARIADB_PASSWORD: passdev
    volumes:
      - db-data-ng-poc:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: ng-poc-phpmyadmin
    restart: always
    ports:
      - '8080:80'
    links:
      - ngdb:db
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root

volumes:
  db-data-ng-poc:
