controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

authentication_token:
    path: /authentication_token
    methods: ['POST']

api_login_check:
    path: /api/login_check
